//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_T_UserManagement
    {
        public int User_Id { get; set; }
        public string User_name { get; set; }
        public string Email_id { get; set; }
        public string Mobile_no { get; set; }
        public string Organisation_name { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Registered_on { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<System.DateTime> Approved_on { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Is_Admin { get; set; }
    }
}
