//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_M_Mailer_Template
    {
        public int Template_Id { get; set; }
        public string Template { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
