//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_T_Specify_Value
    {
        public int id { get; set; }
        public Nullable<int> SpecifyId { get; set; }
        public Nullable<int> Parameter_Id { get; set; }
        public Nullable<decimal> Z14_Value { get; set; }
        public Nullable<decimal> X86_Value { get; set; }
    }
}
