//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_T_Specify
    {
        public int Id { get; set; }
        public string Industry { get; set; }
        public string BusinessImperative { get; set; }
        public string Investment { get; set; }
        public string Analytics { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
